### ISSUE TITLE
Nox Emulator failed

### ISSUE THREAD

**Issue by skelletR** [HuskyDG/magisk-files#12]
i try to install latest canary Magisk-c9701e58-delta(25201), i follow your instruction for nox emulator but it shows me this, what wrong?

![Στιγμιότυπο οθόνης (392)](https://user-images.githubusercontent.com/25982450/184412867-d62133f3-81a9-4cb3-ab6f-595efb383460.png)

**Comment by HuskyDG** [comment]
> i try to install latest canary Magisk-c9701e58-delta(25201), i follow your instruction for nox emulator but it shows me this, what wrong?
> 
> ![Στιγμιότυπο οθόνης (392)](https://user-images.githubusercontent.com/25982450/184412867-d62133f3-81a9-4cb3-ab6f-595efb383460.png)

Try installing again

**Comment by skelletR** [comment]
I reinstalled the nox emulator and try it again, the same result, I don't know why, I can install it inside of your other app, Magisk Terminal Emulator and all normal

**Comment by HuskyDG** [comment]
Try latest canary / debug

**Comment by 0x1997** [comment]
> Try latest canary / debug

Installation succeeded but the app crashed when opening after reboot.

**Comment by HuskyDG** [comment]
Fixed

**Comment by 0x1997** [comment]
> Fixed

Latest canary release from 1 hour ago still crashed after reboot.

**Comment by HuskyDG** [comment]
> > Fixed
> 
> Latest canary release from 1 hour ago still crashed after reboot.

This issue is not yours, please open new issue for it.
